services:
  youtubehd:
    build: .
    ports:
      - "5004:5004"
    volumes:
      - ./config:/config
    environment:
      - BASE_URL=
      - HDHR_DEVICE_ID=12345678
      - HDHR_DEVICE_AUTH=
      - HDHR_FRIENDLY_NAME=YouTubeHDHR
      - POLL_INTERVAL=60
      - CONFIG_PATH=/config/channels.yaml
    restart: unless-stopped
